# Generated by Django 4.1.2 on 2022-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_on',
            new_name='created',
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
